export const RELIGION_CONTENT: any = {
    'Islam': {
        quotes: [
            { text: "Sesungguhnya, sesudah kesulitan itu ada kemudahan", arabic: "إِنَّ مَعَ الْعُسْرِ يُسْرًا", surah: "QS. Al Insyirah: 5" },
            { text: "Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya", arabic: "لَا يُكَلِّفُ ٱللَّهُ نَفْسًا إِلَّا وُسْعَهَا", surah: "QS. Al-Baqarah: 286" },
            { text: "Maka nikmat Tuhan kamu yang manakah yang kamu dustakan?", arabic: "فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ", surah: "QS. Ar-Rahman" },
            { text: "Boleh jadi kamu membenci sesuatu padahal ia amat baik bagimu...", arabic: "وَعَسَىٰ أَن تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَّكُمْ", surah: "QS. Al-Baqarah: 216" },
            { text: "Sesungguhnya orang-orang yang bersabar akan diberi pahala tanpa batas.", arabic: "إِنَّمَا يُوَفَّى الصَّابِرُونَ أَجْرَهُمْ بِغَيْرِ حِسَابٍ", surah: "QS. Az-Zumar: 10" },
            { text: "Dan Dia bersama kamu di mana saja kamu berada.", arabic: "وَهُوَ مَعَكُمْ أَيْنَ مَا كُنْتُمْ", surah: "QS. Al-Hadid: 4" },
            { text: "Jika kamu bersyukur, pasti akan Kutambah nikmat-Ku kepadamu.", arabic: "لَئِنْ شَكَرْتُمْ لَأَزِيدَنَّكُمْ", surah: "QS. Ibrahim: 7" },
            { text: "Janganlah kamu berputus asa dari rahmat Allah.", arabic: "لَا تَقْنَطُوا مِنْ رَحْمَةِ اللَّهِ", surah: "QS. Az-Zumar: 53" },
            { text: "Berdoalah kepada-Ku, niscaya akan Kuperkenankan bagimu.", arabic: "وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ", surah: "QS. Ghafir: 60" },
            { text: "Dan kehidupan dunia ini hanyalah kesenangan yang menipu.", arabic: "وَمَا الْحَيَاةُ الدُّنْيَا إِلَّا مَتَاعُ الْغُرُورِ", surah: "QS. Ali Imran: 185" },
            { text: "Allah akan meninggikan orang-orang yang beriman di antaramu.", arabic: "يَرْفَعِ اللَّهُ الَّذِينَ آمَنُوا مِنْكُمْ", surah: "QS. Al-Mujadalah: 11" },
            { text: "Sesungguhnya Allah tidak mengubah keadaan suatu kaum sehingga mereka mengubahnya sendiri.", arabic: "إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ", surah: "QS. Ar-Ra'd: 11" },
            { text: "Dan Kami lebih dekat kepadanya daripada urat lehernya.", arabic: "وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ", surah: "QS. Qaf: 16" },
            { text: "Maka jangan sekali-kali membiarkan kehidupan dunia ini memperdayakan kamu.", arabic: "فَلَا تَغُرَّنَّكُمُ الْحَيَاةُ الدُّنْيَا", surah: "QS. Fatir: 5" },
            { text: "Dan bersabarlah kamu, sesungguhnya janji Allah adalah benar.", arabic: "فاصبر إن وعد الله حق", surah: "QS. Ar-Rum: 60" },
            { text: "Sesungguhnya rahmat Allah itu dekat kepada orang-orang yang berbuat baik.", arabic: "إِنَّ رَحْمَتَ اللَّهِ قَرِيبٌ مِّنَ الْمُحْسِنِينَ", surah: "QS. Al-A'raf: 56" },
            { text: "Dan barangsiapa bertawakal kepada Allah, niscaya Allah akan mencukupkan keperluannya.", arabic: "وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ", surah: "QS. Ath-Thalaq: 3" },
            { text: "Katakanlah: 'Cukuplah Allah bagiku'.", arabic: "قُلْ حَسْبِيَ اللَّهُ", surah: "QS. Az-Zumar: 38" },
            { text: "Ingatlah, hanya dengan mengingati Allah-lah hati menjadi tenteram.", arabic: "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ", surah: "QS. Ar-Ra'd: 28" },
            { text: "Maka berlomba-lombalah kamu dalam kebaikan.", arabic: "فَاسْتَبِقُوا الْخَيْرَاتِ", surah: "QS. Al-Baqarah: 148" },
            { text: "Dan berpegang teguhlah kamu semuanya pada tali Allah.", arabic: "وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا", surah: "QS. Ali Imran: 103" },
            { text: "Jadilah pemaaf dan suruhlah orang mengerjakan yang makruf.", arabic: "خُذِ الْعَفْوَ وَأْمُرْ بِالْعُرْفِ", surah: "QS. Al-A'raf: 199" },
            { text: "Tuhanmu tidak meninggalkanmu dan tidak pula membencimu.", arabic: "مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ", surah: "QS. Ad-Duha: 3" },
            { text: "Allah pelindung bagi orang-orang yang beriman.", arabic: "اللَّهُ وَلِيُّ الَّذِينَ آمَنُوا", surah: "QS. Al-Baqarah: 257" },
            { text: "Sesungguhnya Kami milik Allah dan kepada-Nyalah Kami kembali.", arabic: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ", surah: "QS. Al-Baqarah: 156" },
            { text: "Dan tolong-menolonglah kamu dalam kebaikan dan takwa.", arabic: "وَتَعَاوَنُوا عَلَى الْبِرِّ وَالتَّقْوَىٰ", surah: "QS. Al-Ma'idah: 2" },
            { text: "Sesungguhnya perbuatan baik itu menghapus perbuatan buruk.", arabic: "إِنَّ الْحَسَنَاتِ يُذْهِبْنَ السَّيِّئَاتِ", surah: "QS. Hud: 114" },
            { text: "Maka sembahlah Allah dengan memurnikan ibadah kepada-Nya.", arabic: "فَاعْبُدِ اللَّهَ مُخْلِصًا لَهُ الدِّينَ", surah: "QS. Az-Zumar: 2" },
            { text: "Tiada suatu ucapan pun yang diucapkannya melainkan ada di sisinya malaikat pengawas.", arabic: "مَا يَلْفِظُ مِنْ قَوْلٍ إِلَّا لَدَيْهِ رَقِيبٌ عَتِيدٌ", surah: "QS. Qaf: 18" },
            { text: "Barang siapa bersungguh-sungguh, dia akan berhasil.", arabic: "مَنْ جَدَّ وَجَدَ", surah: "Mahfuzhat" },
            { text: "Kesabaran adalah kunci kemudahan.", arabic: "الصَّبْرُ مِفْتَاحُ الْفَرَجِ", surah: "Mahfuzhat" },
            { text: "Ilmu tanpa amal bak pohon tanpa buah.", arabic: "اَلْعِلْمُ بِلاَ عَمَلٍ كَالشَّجَرِ بِلاَ ثَمَرٍ", surah: "Mahfuzhat" },
            { text: "Katakanlah kebenaran itu walaupun pahit.", arabic: "قُلِ الحَقَّ وَلَوْ كَانَ مُرًّا", surah: "Hadits" },
            { text: "Kebersihan itu sebagian dari Iman.", arabic: "النَّظَافَةُ مِنَ الْإِيمَانِ", surah: "Hadits" },
            { text: "Tangan di atas lebih baik daripada tangan di bawah.", arabic: "الْيَدُ الْعُلْيَا خَيْرٌ مِنَ الْيَدِ السُّفْلَى", surah: "Hadits" },
            { text: "Sebaik-baik manusia adalah yang paling bermanfaat bagi orang lain.", arabic: "خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ", surah: "Hadits" },
            { text: "Menuntut ilmu itu wajib bagi setiap muslim.", arabic: "طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ", surah: "Hadits" },
            { text: "Senyummu di hadapan saudaramu adalah sedekah.", arabic: "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ", surah: "Hadits" },
            { text: "Surga itu di bawah telapak kaki ibu.", arabic: "الْجَنَّةُ تَحْتَ أَقْدَامِ الْأُمَّهَاتِ", surah: "Hadits" },
            { text: "Cintailah saudaramu seperti mencintai dirimu sendiri.", arabic: "أَحِبَّ لِأَخِيكَ مَا تُحِبُّ لِنَفْسِكَ", surah: "Hadits" }
        ]
    },
    'Kristen': {
        quotes: [
            { text: "Segala perkara dapat kutanggung di dalam Dia yang memberi kekuatan kepadaku.", source: "Filipi 4:13" },
            { text: "Sebab Aku ini mengetahui rancangan-rancangan apa yang ada pada-Ku mengenai kamu...", source: "Yeremia 29:11" },
            { text: "Percayalah kepada Tuhan dengan segenap hatimu, dan janganlah bersandar kepada pengertianmu sendiri.", source: "Amsal 3:5" },
            { text: "Janganlah takut, sebab Aku menyertai engkau.", source: "Yesaya 41:10" },
            { text: "Hati yang gembira adalah obat yang manjur.", source: "Amsal 17:22" },
            { text: "Tuhan adalah gembalaku, takkan kekurangan aku.", source: "Mazmur 23:1" },
            { text: "Kasih itu sabar; kasih itu murah hati.", source: "1 Korintus 13:4" },
            { text: "Bersukacitalah senantiasa. Tetaplah berdoa.", source: "1 Tesalonika 5:16-17" },
            { text: "Janganlah kamu kuatir tentang apapun juga.", source: "Filipi 4:6" },
            { text: "Damai sejahtera Allah yang melampaui segala akal akan memelihara hati dan pikiranmu.", source: "Filipi 4:7" },
            { text: "Apa pun juga yang kamu perbuat, perbuatlah dengan segenap hatimu seperti untuk Tuhan.", source: "Kolose 3:23" },
            { text: "Kuatkan dan teguhkanlah hatimu, janganlah takut.", source: "Yosua 1:9" },
            { text: "Allah turut bekerja dalam segala sesuatu untuk mendatangkan kebaikan.", source: "Roma 8:28" },
            { text: "Janganlah kita jemu-jemu berbuat baik.", source: "Galatia 6:9" },
            { text: "Pencobaan yang kamu alami tidak melebihi kekuatan manusia.", source: "1 Korintus 10:13" },
            { text: "Tetapi buah Roh ialah: kasih, sukacita, damai sejahtera.", source: "Galatia 5:22" },
            { text: "Sebab Aku, TUHAN, Allahmu, memegang tangan kananmu.", source: "Yesaya 41:13" },
            { text: "Firman-Mu itu pelita bagi kakiku dan terang bagi jalanku.", source: "Mazmur 119:105" },
            { text: "Marilah kepada-Ku, semua yang letih lesu dan berbeban berat.", source: "Matius 11:28" },
            { text: "Dalam dunia ini kamu akan mengalami kesukaran. Tetapi kuatkanlah hatimu!", source: "Yohanes 16:33" },
            { text: "Orang yang sabar melebihi seorang pahlawan.", source: "Amsal 16:32" },
            { text: "Serahkanlah segala kekuatiranmu kepada-Nya, sebab Ia yang memelihara kamu.", source: "1 Petrus 5:7" },
            { text: "Jika Allah di pihak kita, siapakah yang akan melawan kita?", source: "Roma 8:31" },
            { text: "Hendaklah kamu murah hati, sama seperti Bapamu adalah murah hati.", source: "Lukas 6:36" },
            { text: "Janganlah membalas kejahatan dengan kejahatan.", source: "Roma 12:17" },
            { text: "Hiduplah dalam perdamaian dengan semua orang.", source: "Ibrani 12:14" },
            { text: "Rancangan-Ku bukanlah rancanganmu, dan jalanmu bukanlah jalan-Ku.", source: "Yesaya 55:8" },
            { text: "Tetapi orang yang menanti-nantikan TUHAN mendapat kekuatan baru.", source: "Yesaya 40:31" },
            { text: "Aku datang, supaya mereka mempunyai hidup dalam segala kelimpahan.", source: "Yohanes 10:10" },
            { text: "Dan inilah hidup yang kekal itu, yaitu bahwa mereka mengenal Engkau.", source: "Yohanes 17:3" },
            { text: "Janganlah kamu menjadi serupa dengan dunia ini.", source: "Roma 12:2" },
            { text: "Kasihilah sesamamu manusia seperti dirimu sendiri.", source: "Matius 22:39" },
            { text: "Berdoalah satu sama lain, supaya kamu sembuh.", source: "Yakobus 5:16" },
            { text: "Kebajikan dan kemurahan belaka akan mengikuti aku seumur hidupku.", source: "Mazmur 23:6" },
            { text: "Tuhan adalah cahaya dan keselamatanku, kepada siapakah aku harus takut?", source: "Mazmur 27:1" },
            { text: "Engkau memberitahukan kepadaku jalan kehidupan.", source: "Mazmur 16:11" },
            { text: "Tetapi carilah dahulu Kerajaan Allah dan kebenarannya.", source: "Matius 6:33" },
            { text: "Nama TUHAN adalah menara yang kuat, ke sanalah orang benar berlari.", source: "Amsal 18:10" },
            { text: "Sebab hidup kami adalah hidup karena percaya, bukan karena melihat.", source: "2 Korintus 5:7" },
            { text: "Kasih tidak menyimpan kesalahan orang lain.", source: "1 Korintus 13:5" }
        ]
    },
    'Katolik': {
        quotes: [
            { text: "Marilah kepada-Ku, semua yang letih lesu dan berbeban berat, Aku akan memberi kelegaan kepadamu.", source: "Matius 11:28" },
            { text: "Tuhan adalah gembalaku, takkan kekurangan aku.", source: "Mazmur 23:1" },
            { text: "Lakukanlah segala pekerjaanmu dalam kasih!", source: "1 Korintus 16:14" },
            { text: "Sebab bagi Allah tidak ada yang mustahil.", source: "Lukas 1:37" },
            { text: "Aku menyertai kamu senantiasa sampai kepada akhir zaman.", source: "Matius 28:20" },
            { text: "Berbahagialah orang yang membawa damai, karena mereka akan disebut anak-anak Allah.", source: "Matius 5:9" },
            { text: "Tuhan itu dekat kepada orang-orang yang patah hati.", source: "Mazmur 34:19" },
            { text: "Hendaklah kamu kudus, sebab Aku ini kudus.", source: "1 Petrus 1:16" },
            { text: "Semoga damai sejahtera Kristus memerintah dalam hatimu.", source: "Kolose 3:15" },
            { text: "Terpujilah Tuhan, sumber segala penghiburan.", source: "2 Korintus 1:3" },
            { text: "Jangan takut, Maria, sebab engkau beroleh kasih karunia di hadapan Allah.", source: "Lukas 1:30" },
            { text: "Aku ini hamba Tuhan; jadilah padaku menurut perkataanmu itu.", source: "Lukas 1:38" },
            { text: "Inilah perintah-Ku, yaitu supaya kamu saling mengasihi.", source: "Yohanes 15:12" },
            { text: "Lakukanlah ini sebagai kenangan akan Aku.", source: "Lukas 22:19" },
            { text: "Kasih tidak mencari kepentingan diri sendiri.", source: "1 Korintus 13:5" },
            { text: "Barangsiapa rendah hati akan ditinggikan.", source: "Lukas 14:11" },
            { text: "Muliakanlah Tuhan bersama-sama dengan aku.", source: "Mazmur 34:4" },
            { text: "Teranglah itu bercahaya di dalam kegelapan.", source: "Yohanes 1:5" },
            { text: "Beritakanlah Injil kepada segala makhluk.", source: "Markus 16:15" },
            { text: "Allah adalah kasih, dan barangsiapa tetap berada di dalam kasih, ia tetap berada di dalam Allah.", source: "1 Yohanes 4:16" },
            { text: "Doakanlah mereka yang menganiaya kamu.", source: "Matius 5:44" },
            { text: "Siapa yang mengasihi Aku, ia akan menuruti firman-Ku.", source: "Yohanes 14:23" },
            { text: "Segala sesuatu yang kamu kehendaki supaya orang perbuat kepadamu, perbuatlah demikian juga kepada mereka.", source: "Matius 7:12" },
            { text: "Jangan biarkan hatimu gelisah. Percayalah kepada Allah.", source: "Yohanes 14:1" },
            { text: "Kita mencintai, karena Allah lebih dahulu mencintai kita.", source: "1 Yohanes 4:19" },
            { text: "Kasih menutupi banyak sekali dosa.", source: "1 Petrus 4:8" },
            { text: "Kesetiaan Tuhan untuk selama-lamanya.", source: "Mazmur 117:2" },
            { text: "Tuhan memberkati engkau dan melindungi engkau.", source: "Bilangan 6:24" },
            { text: "Sebab di mana ada hartamu, di situ juga hatimu berada.", source: "Matius 6:21" },
            { text: "Warta sukacita bagi orang miskin.", source: "Lukas 4:18" },
            { text: "Jadilah saksi-Ku sampai ke ujung bumi.", source: "Kisah Para Rasul 1:8" },
            { text: "Hendaklah sedekahmu itu diberikan dengan tersembunyi.", source: "Matius 6:4" },
            { text: "Berdoalah supaya kamu jangan jatuh ke dalam pencobaan.", source: "Lukas 22:46" },
            { text: "Roh memang penurut, tetapi daging lemah.", source: "Matius 26:41" },
            { text: "Janganlah kamu menghakimi, supaya kamu tidak dihakimi.", source: "Matius 7:1" },
            { text: "Carilah, maka kamu akan mendapat.", source: "Matius 7:7" },
            { text: "Berbahagialah kamu, jika karena Aku kamu dicela.", source: "Matius 5:11" },
            { text: "Hiduplah dalam damai satu dengan yang lain.", source: "Markus 9:50" },
            { text: "Kerjakanlah keselamatanmu dengan takut dan gentar.", source: "Filipi 2:12" },
            { text: "Biarkan anak-anak itu datang kepada-Ku.", source: "Matius 19:14" }
        ]
    },
    'Buddha': {
        quotes: [
            { text: "Pikiran adalah pelopor dari segala sesuatu, pikiran adalah pemimpin, pikiran adalah pembentuk.", source: "Dhammapada" },
            { text: "Kebencian tidak akan pernah berakhir dengan kebencian; kebencian hanya berakhir dengan cinta kasih.", source: "Ajaran Buddha" },
            { text: "Jangan hidup di masa lalu, jangan memimpikan masa depan, konsentrasikan pikiran pada saat sekarang.", source: "Ajaran Buddha" },
            { text: "Ribuan lilin dapat dinyalakan dari satu lilin dan nyalanya tidak akan berkurang.", source: "Ajaran Buddha" },
            { text: "Kesehatan adalah pemberian yang paling baik, kepuasan adalah kekayaan yang terbesar.", source: "Dhammapada" },
            { text: "Kemenangan melahirkan kebencian; yang kalah hidup dalam penderitaan.", source: "Ajaran Buddha" },
            { text: "Tidak ada api yang menyamai nafsu, tidak ada kejahatan yang menyamai noda kebencian.", source: "Dhammapada" },
            { text: "Pikiran yang terkendali adalah sumber kebahagiaan.", source: "Ajaran Buddha" },
            { text: "Jalan kebenaran itu indah dan memberikan kedamaian.", source: "Ajaran Buddha" },
            { text: "Keheningan adalah emas bagi mereka yang bijaksana.", source: "Ajaran Buddha" },
            { text: "Akar dari penderitaan adalah kemelekatan.", source: "Ajaran Buddha" },
            { text: "Segala sesuatu yang memiliki awal, pasti memiliki akhir.", source: "Ajaran Buddha" },
            { text: "Jadilah pelita bagi dirimu sendiri.", source: "Ajaran Buddha" },
            { text: "Kebahagiaan tidak bergantung pada apa yang kamu miliki, tapi siapa dirimu.", source: "Ajaran Buddha" },
            { text: "Kesabaran adalah asketisme yang paling tinggi.", source: "Ajaran Buddha" },
            { text: "Satu kata yang membawa kedamaian lebih baik daripada seribu kata kosong.", source: "Ajaran Buddha" },
            { text: "Kualitas diri ditentukan oleh pikiran dan tindakan.", source: "Ajaran Buddha" },
            { text: "Cinta kasih adalah satu-satunya jawaban untuk kebencian.", source: "Ajaran Buddha" },
            { text: "Kebajikan melindungi mereka yang mempraktikkannya.", source: "Ajaran Buddha" },
            { text: "Lepaskan beban masa lalu, temukan kedamaian sekarang.", source: "Ajaran Buddha" },
            { text: "Kebenaran akan membebaskanmu dari ketidaktahuan.", source: "Ajaran Buddha" },
            { text: "Lakukan kebaikan meskipun kecil, karena itu akan berakumulasi.", source: "Ajaran Buddha" },
            { text: "Berbicara benar, bertindak benar, hidup benar.", source: "Jalan Mulia Beruas Delapan" },
            { text: "Kemurnian dan kekotoran bergantung pada diri sendiri.", source: "Ajaran Buddha" },
            { text: "Pengetahuan tanpa praktik adalah kesia-siaan.", source: "Ajaran Buddha" },
            { text: "Disiplin diri adalah kunci kebebasan.", source: "Ajaran Buddha" },
            { text: "Jangan meremehkan kejahatan sekecil apapun.", source: "Dhammapada" },
            { text: "Seperti batu karang yang tak tergoyahkan oleh badai.", source: "Ajaran Buddha" },
            { text: "Pancarkan metta (cinta kasih) ke segala arah.", source: "Metta Sutta" },
            { text: "Kehidupan ini adalah perubahan yang terus-menerus (Anicca).", source: "Ajaran Buddha" },
            { text: "Berusahalah dengan sungguh-sungguh untuk mencapai pembebasan.", source: "Khotbah Terakhir Buddha" },
            { text: "Satu momen perhatian murni lebih berharga daripada seribu tahun kelengahan.", source: "Ajaran Buddha" },
            { text: "Jangan iri pada keberuntungan orang lain.", source: "Ajaran Buddha" },
            { text: "Sifat marah bagaikan menggenggam bara api.", source: "Ajaran Buddha" },
            { text: "Kerendahan hati adalah tanda kebijaksanaan.", source: "Ajaran Buddha" },
            { text: "Berbagi kebahagiaan tidak akan mengurangi milikmu.", source: "Ajaran Buddha" },
            { text: "Temukan kedamaian dalam kesendirian.", source: "Ajaran Buddha" },
            { text: "Welas asih adalah inti dari ajaran spiritual.", source: "Ajaran Buddha" },
            { text: "Pikiran yang tenang membawa kekuatan batin.", source: "Ajaran Buddha" },
            { text: "Kebijaksanaan adalah pelita dalam kegelapan dunia.", source: "Ajaran Buddha" }
        ]
    },
    'Hindu': {
        quotes: [
            { text: "Lakukan pekerjaanmu dengan keseimbangan (yoga), lepaskan keterikatan pada hasil akhir.", source: "Bhagavad Gita" },
            { text: "Tugasmu adalah bertindak, bukan pada hasil dari tindakanmu itu.", source: "Bhagavad Gita" },
            { text: "Mereka yang melihat aksi dalam inaksi, dan inaksi dalam aksi, adalah bijaksana di antara manusia.", source: "Bhagavad Gita" },
            { text: "Jiwa tidak pernah lahir dan tidak pernah mati.", source: "Bhagavad Gita" },
            { text: "Pikiran adalah sahabat bagi mereka yang telah menaklukkannya.", source: "Bhagavad Gita" },
            { text: "Kendalikan indramu, kendalikan pikiranmu, temukan kedamaian.", source: "Bhagavad Gita" },
            { text: "Kebenaran adalah satu, namun orang bijak menyebutnya dengan banyak nama.", source: "Reg Veda" },
            { text: "Seluruh dunia adalah satu keluarga (Vasudhaiva Kutumbakam).", source: "Maha Upanishad" },
            { text: "Jangan terikat pada buah dari tindakanmu.", source: "Bhagavad Gita" },
            { text: "Kemarahan membawa delusi, dan delusi membawa kehancuran memori.", source: "Bhagavad Gita" },
            { text: "Lepaskan semua bentuk ketakutan dan keraguan.", source: "Bhagavad Gita" },
            { text: "Ketenangan adalah disiplin pikiran yang tertinggi.", source: "Bhagavad Gita" },
            { text: "Seseorang menjadi apa yang ia yakini.", source: "Bhagavad Gita" },
            { text: "Lakukan kewajibanmu demi keharmonisan dunia.", source: "Bhagavad Gita" },
            { text: "Kesabaran adalah kekuatan bagi mereka yang lemah.", source: "Ajaran Hindu" },
            { text: "Pengabdian yang tulus menghubungkanmu dengan Yang Ilahi.", source: "Bhagavad Gita" },
            { text: "Hiduplah dalam dharma (kebenaran).", source: "Weda" },
            { text: "Pengetahuan adalah senjata yang paling ampuh.", source: "Mahabharata" },
            { text: "Ketidakegoisan adalah jalan menuju kebebasan.", source: "Bhagavad Gita" },
            { text: "Hargai setiap makhluk hidup karena di dalamnya ada Atman.", source: "Upanishad" },
            { text: "Disiplin diri adalah fondasi kesuksesan.", source: "Bhagavad Gita" },
            { text: "Waktu adalah penyembuh segalanya.", source: "Mahabharata" },
            { text: "Kejujuran adalah fondasi dari karakter yang kuat.", source: "Weda" },
            { text: "Kebahagiaan sejati datang dari dalam diri.", source: "Bhagavad Gita" },
            { text: "Berikan bantuan tanpa mengharapkan imbalan.", source: "Bhagavad Gita" },
            { text: "Kualitas pikiran menentukan kualitas hidup.", source: "Bhagavad Gita" },
            { text: "Meditasi membawa kejernihan dan visi.", source: "Yogasutra" },
            { text: "Hormati orang tua dan guru sebagai perwakilan Tuhan.", source: "Weda" },
            { text: "Tetaplah teguh dalam keyakinanmu.", source: "Bhagavad Gita" },
            { text: "Keinginan yang tak terkendali adalah musuh terbesarmu.", source: "Bhagavad Gita" },
            { text: "Temukan kesatuan di tengah keberagaman.", source: "Upanishad" },
            { text: "Jangan biarkan emosi menguasai logikamu.", source: "Bhagavad Gita" },
            { text: "Kekuatan batin melampaui kekuatan fisik.", source: "Mahabharata" },
            { text: "Layani sesama sebagai bentuk ibadah.", source: "Ajaran Hindu" },
            { text: "Hiduplah dengan sederhana agar orang lain bisa hidup.", source: "Ajaran Hindu" },
            { text: "Kebijaksanaan adalah buah dari pengalaman dan refleksi.", source: "Bhagavad Gita" },
            { text: "Tetaplah rendah hati saat mencapai puncak kesuksesan.", source: "Bhagavad Gita" },
            { text: "Berani karena benar, takut karena salah.", source: "Ajaran Hindu" },
            { text: "Harmoni dengan alam membawa kedamaian jiwa.", source: "Weda" },
            { text: "Tujuan akhir hidup adalah kebebasan (Moksha).", source: "Weda" }
        ]
    },
    'Konghucu': {
        quotes: [
            { text: "Kesalahan terbesar manusia adalah tidak memperbaiki kesalahan yang diketahuinya.", source: "Kong Fucu" },
            { text: "Hidup ini benar-benar sederhana, tapi kita bersikeras membuatnya rumit.", source: "Kong Fucu" },
            { text: "Berharganya sebuah permata tidak bisa diasah tanpa gesekan, begitu pula manusia tak bisa sempurna tanpa cobaan.", source: "Kong Fucu" },
            { text: "Jangan lakukan pada orang lain apa yang tidak ingin dilakukan padamu.", source: "Kong Fucu" },
            { text: "Keunggulan sejati adalah menaklukkan diri sendiri.", source: "Kong Fucu" },
            { text: "Belajarlah tanpa henti dan praktikkanlah.", source: "Kong Fucu" },
            { text: "Kejujuran adalah jalan surgawi.", source: "Kong Fucu" },
            { text: "Seorang Junzi (insan budiman) selalu tenang dan lapang dada.", source: "Kong Fucu" },
            { text: "Mengenal diri sendiri adalah awal dari kebijaksanaan.", source: "Kong Fucu" },
            { text: "Hormatilah orang tua agar anak-anakmu menghormatimu.", source: "Kong Fucu" },
            { text: "Ketulusan adalah pangkal dan akhir dari segala sesuatu.", source: "Kong Fucu" },
            { text: "Berbicara harus tepat, bertindak harus nyata.", source: "Kong Fucu" },
            { text: "Kebaktian kepada orang tua adalah akar dari segala kebajikan.", source: "Xiao Jing" },
            { text: "Jika kamu ingin sukses, bantu juga orang lain untuk sukses.", source: "Kong Fucu" },
            { text: "Kesetiaan dan dapat dipercaya adalah prinsip utama.", source: "Kong Fucu" },
            { text: "Orang bijak tidak pernah bingung; orang berani tidak pernah takut.", source: "Kong Fucu" },
            { text: "Belajar tanpa berpikir adalah sia-sia; berpikir tanpa belajar adalah berbahaya.", source: "Kong Fucu" },
            { text: "Melihat apa yang benar dan tidak melakukannya adalah kelemahan.", source: "Kong Fucu" },
            { text: "Kesempurnaan diri dimulai dari keteraturan hati.", source: "Kong Fucu" },
            { text: "Seorang pemimpin harus memberikan teladan yang baik.", source: "Kong Fucu" },
            { text: "Jangan bergaul dengan orang yang tidak lebih baik darimu.", source: "Kong Fucu" },
            { text: "Marah adalah hukuman bagi diri sendiri atas kesalahan orang lain.", source: "Kong Fucu" },
            { text: "Kemanfaatan ilmu terletak pada pengamalannya.", source: "Kong Fucu" },
            { text: "Kemanusiaan (Ren) adalah mencintai sesama manusia.", source: "Kong Fucu" },
            { text: "Tetaplah teguh pada prinsip kebenaran meskipun sulit.", source: "Kong Fucu" },
            { text: "Keluarga yang harmonis adalah kunci kekuatan negara.", source: "Kong Fucu" },
            { text: "Disiplin adalah jembatan antara cita-cita dan pencapaian.", source: "Kong Fucu" },
            { text: "Jangan pernah berhenti belajar meski rambut telah memutih.", source: "Kong Fucu" },
            { text: "Kesopanan adalah hiasan dari karakter yang mulia.", source: "Kong Fucu" },
            { text: "Keberanian tanpa kebenaran adalah kekerasan.", source: "Kong Fucu" },
            { text: "Orang yang melakukan kesalahan dan tidak memperbaikinya, melakukan kesalahan lagi.", source: "Kong Fucu" },
            { text: "Tuntutlah dirimu sendiri, jangan menuntut orang lain.", source: "Kong Fucu" },
            { text: "Segala sesuatu memiliki keindahan, tapi tidak semua orang melihatnya.", source: "Kong Fucu" },
            { text: "Diam adalah kawan sejati yang tak pernah mengkhianati.", source: "Kong Fucu" },
            { text: "Kesuksesan tergantung pada persiapan sebelumnya.", source: "Kong Fucu" },
            { text: "Kekuatan karakter datang dari integritas.", source: "Kong Fucu" },
            { text: "Berperilakulah adil meskipun terhadap musuhmu.", source: "Kong Fucu" },
            { text: "Kehidupan yang bermakna adalah kehidupan yang bermanfaat.", source: "Kong Fucu" },
            { text: "Hiduplah selaras dengan hukum alam (Tian Li).", source: "Kong Fucu" },
            { text: "Cintailah pekerjaanmu agar kamu tidak pernah bekerja sehari pun.", source: "Kong Fucu" }
        ]
    },
    'Lainnya': {
        quotes: [
            { text: "Hiduplah seakan engkau akan mati besok. Belajarlah seakan engkau akan hidup selamanya.", source: "Motivasi Harian" },
            { text: "Rahasia dari masa depan yang sukses adalah tersembunyi di dalam rutinitas harianmu.", source: "Motivasi Harian" },
            { text: "Jangan pernah menyerah pada impianmu hanya karena waktu yang dibutuhkan.", source: "Motivasi Harian" },
            { text: "Perjalanan seribu mil dimulai dengan satu langkah kecil.", source: "Lao Tzu" },
            { text: "Keberhasilan bukanlah akhir, kegagalan bukanlah kehancuran.", source: "Motivasi Harian" },
            { text: "Percayalah kamu bisa, dan kamu sudah setengah jalan di sana.", source: "Theodore Roosevelt" },
            { text: "Masa depan adalah milik mereka yang percaya pada keindahan mimpi mereka.", source: "Eleanor Roosevelt" },
            { text: "Fokuslah pada kemajuan, bukan kesempurnaan.", source: "Motivasi Harian" },
            { text: "Waktumu terbatas, jangan habiskan untuk hidup sebagai orang lain.", source: "Steve Jobs" },
            { text: "Satu-satunya cara melakukan pekerjaan hebat adalah mencintai apa yang dilakukan.", source: "Steve Jobs" },
            { text: "Jangan biarkan hari kemarin menghabiskan terlalu banyak waktu hari ini.", source: "Will Rogers" },
            { text: "Kesempatan tidak terjadi, kau yang menciptakannya.", source: "Chris Grosser" },
            { text: "Jangan menunggu, waktu tidak akan pernah 'tepat'.", source: "Napoleon Hill" },
            { text: "Jika kamu lelah, belajarlah untuk beristirahat, bukan menyerah.", source: "Banksy" },
            { text: "Hidup adalah 10% apa yang terjadi padamu dan 90% bagaimana kau meresponsnya.", source: "Charles R. Swindoll" },
            { text: "Disiplin melakukan apa yang harus dilakukan, meskipun tidak ingin.", source: "Motivasi Harian" },
            { text: "Kesuksesan adalah berjalan dari kegagalan ke kegagalan tanpa kehilangan antusiasme.", source: "Winston Churchill" },
            { text: "Kualitas hidupmu ditentukan oleh kualitas pikiranmu.", source: "Motivasi Harian" },
            { text: "Berani mengambil risiko adalah harga dari sebuah keberhasilan.", source: "Motivasi Harian" },
            { text: "Jadilah perubahan yang ingin kau lihat di dunia.", source: "Mahatma Gandhi" },
            { text: "Ketekunan mengalahkan segalanya, bahkan bakat.", source: "Motivasi Harian" },
            { text: "Iman adalah mengambil langkah pertama meskipun tidak melihat seluruh tangga.", source: "Martin Luther King Jr." },
            { text: "Kebahagiaan adalah ketika apa yang kau pikirkan, kau katakan, dan kau lakukan berada dalam harmoni.", source: "Mahatma Gandhi" },
            { text: "Jangan biarkan ketakutan akan kegagalan lebih besar daripada antusiasme akan keberhasilan.", source: "Robert Kiyosaki" },
            { text: "Apa yang kita capai secara internal akan mengubah realitas eksternal.", source: "Plutarch" },
            { text: "Hiduplah dengan tujuan, bertindaklah dengan kasih.", source: "Motivasi Harian" },
            { text: "Kesulitan seringkali mempersiapkan orang biasa untuk nasib yang luar biasa.", source: "C.S. Lewis" },
            { text: "Jangan menghitung hari, buatlah hari-hari itu berarti.", source: "Muhammad Ali" },
            { text: "Kelemahan terbesar kita adalah menyerah.", source: "Thomas Edison" },
            { text: "Tantangan adalah apa yang membuat hidup menarik.", source: "Joshua J. Marine" },
            { text: "Aksi adalah kunci dasar untuk semua kesuksesan.", source: "Pablo Picasso" },
            { text: "Masa depanmu ditentukan oleh apa yang kau lakukan hari ini.", source: "Motivasi Harian" },
            { text: "Kebaikan adalah bahasa yang bisa didengar oleh orang tuli dan dilihat oleh orang buta.", source: "Mark Twain" },
            { text: "Jangan pernah menyesali hari dalam hidupmu.", source: "Motivasi Harian" },
            { text: "Apa yang kamu tanam hari ini akan kamu panen esok.", source: "Motivasi Harian" },
            { text: "Hati yang bersyukur adalah magnet bagi keajaiban.", source: "Motivasi Harian" },
            { text: "Kesuksesan sejati adalah ketika kamu bisa membantu orang lain sukses.", source: "Motivasi Harian" },
            { text: "Jangan bandingkan bab pertama hidupmu dengan bab kedua puluh orang lain.", source: "Motivasi Harian" },
            { text: "Konsistensi adalah kunci untuk membuka pintu potensi.", source: "Motivasi Harian" },
            { text: "Hari ini adalah hadiah, itulah sebabnya disebut 'present'.", source: "Motivasi Harian" }
        ]
    }
};
